# See https://cloud.google.com/appengine/docs/standard/python3/config/appref for all options.

runtime: python37

env_variables:
  TRAVIS_TOKEN_ENCRYPTED: CiQABCLzEEg7j61hnaT9vSXIT3388+A041quF/7zeg7KBapnm5gSQADsoWgyr5mysMpjLGu3WE9Pq4xXNSMtO0+qEzlvra9FVyuCM0+jmxmCPyAEID3dRH3P7fe2KLqXNqFap7/DV5o=
