# See https://cloud.google.com/appengine/docs/standard/python3/config/appref for all options.

runtime: python37

env_variables:
  TRAVIS_TOKEN_ENCRYPTED: CiQABCLzEBhEt1AZ3jhRvQZ2NA1ulmF76mCSwOacYSotbd6P8oASPwDsoWgyqy0ByNPQt6CM9cOpzeBEOTrCfrVKYvl63HVF7sFNUOQCnNpj6ph0P3FBnGeJ2EiwqogB9jerU/FMFA==
